# Generated by Django 5.2 on 2025-04-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referenceApp', '0002_remove_post_date_posted_alter_post_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='fallback.png', null=True, upload_to='posts/'),
        ),
    ]
