# Generated by Django 5.2 on 2025-04-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='editing',
            field=models.BooleanField(default=False),
        ),
    ]
