# Generated by Django 5.2 on 2025-04-26 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoManager', '0002_todo_editing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='editing',
        ),
    ]
